<img src="https://raw.githubusercontent.com/sebastianVP/sebastianVP/main/toulouselautrec_logo.jpg" alt= "LOGO CAT" width=400 height=400 align = "right">

<br>
<h1><font color="#7F000E" size=5>TOULOUSE LAUTREC </font></h1>
<h1><font color="#7F000R" size=6> DATA SCIENCE MACHINE LEARNING</font></h1>
<h1><font color="#7F000E" size=4> ANALISIS DE DATOS CON PYTHON
 </font></h1>
<br>
<br>
<div style="text-align:left">
<font color="#7F000E" size=3> Ing. Alexander Valdez</font><br>
<font color="#7F000E" size=3> Curso 2271, Clases Lunes y Miercoles 20:00-22:30pm </font><br>
<font color="#7F000e" size=3> Quinta Sesión - 4</font><br>
</div>

#**Regresión lineal multiple**
La regresión lineal múltiple es la gran técnica estadística para comprobar hipótesis y relaciones explicativas.

![DiferenciaRegresionLineal](https://miro.medium.com/max/638/1*-DWX3ZJaj0bvM1aPxcrtyA.jpeg)

##**Descripción de la base de datos**

Datos obtenidos de páginas de internet inmoviliarias de viviendas ubicadas en Melbourne Australia, a continuación se presenta la descripción de las caracteristicas.

**Suburb**: Suburb

**Address**: Address

**Rooms**: Number of rooms

**Price**: Price in dollars

**Method**: S - property sold; SP - property sold prior; PI - property passed in; PN - sold prior not disclosed; SN - sold not disclosed; NB - no bid; VB - vendor bid; W - withdrawn prior to auction; SA - sold after auction; SS - sold after auction price not disclosed. N/A - price or highest bid not available.

**Type**: br - bedroom(s); h - house,cottage,villa, semi,terrace; u - unit, duplex; t - townhouse; dev site - development site; o res - other residential.

**SellerG**: Real Estate Agent

**Date**: Date sold

**Distance**: Distance from CBD

**Regionname**: General Region (West, North West, North, North east ...etc)

**Propertycount**: Number of properties that exist in the suburb.

**Bedroom2**: Scraped # of Bedrooms (from different source)

**Bathroom**: Number of Bathrooms

**Car**: Number of carspots

**Landsize**: Land Size

**BuildingArea**: Building Size

**YearBuilt**: Year the house was built

**CouncilArea**: Governing council for the area

**Lattitude**: Self explanitory

**Longtitude**: Self explanitory

LINK DE DESCARGA DEL CONJUNTO DE DATOS:

https://www.kaggle.com/datasets/glovepm/melbourne-housing

## **Explorasión de la base de datos**

In [ ]:
#importar la libreria de pandas para leer los datos
import pandas as pd

In [ ]:
datos = pd.read_csv("Melbourne_housing.csv",header=387)

In [ ]:
datos.head()

,South MelbourneSuburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Week,CPI,LastCPI,Distance2
0,Footscray,202/51 Gordon St,1,u,85000,PI,Burnham,03-09-2016,6.4,32,108.6,108.2,8.1
1,Caulfield,30 Pyne St,4,h,131000,PI,Rodney,25-02-2017,8.9,57,109.4,108.6,12.8
2,Coburg,171 Moreland Rd,4,h,145000,PI,Jellis,04-06-2016,7.8,19,108.2,108.4,6.8
3,Albion,8/6 Ridley St,1,u,145000,PI,Biggin,28-05-2016,13.9,18,108.2,108.4,14.4
4,Albion,10/117 Anderson Rd,1,u,185000,S,hockingstuart,22-08-2016,13.9,30,108.6,108.2,14.1

In [ ]:
datos = datos.dropna()

In [ ]:
datos.shape

(8996, 13)

In [ ]:
import statsmodels.api as sm
from scipy import stats


X = datos.iloc[:,[2,8,9,10,11,12]]
y = datos.Price

In [ ]:
type(X)

pandas.core.frame.DataFrame

In [ ]:
new_df = datos.iloc[:,[2,8,9,10,11,12,4]]

In [ ]:
new_df.corr()['Price']

Rooms        0.560370
Distance    -0.071556
Week         0.059796
CPI          0.063364
LastCPI      0.021798
Distance2   -0.009899
Price        1.000000
Name: Price, dtype: float64

In [ ]:
type(datos['Price'])

pandas.core.series.Series

#**Modelo lineal Multiple**

In [ ]:
import statsmodels.api as sm
from scipy import stats


X = datos.iloc[:,[2,8,9,10,11,12]]
y = datos.Price

X2 = sm.add_constant(X)



est = sm.OLS(y, X2)
est2 = est.fit()


print(est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.382
Model:                            OLS   Adj. R-squared:                  0.382
Method:                 Least Squares   F-statistic:                     927.9
Date:                Thu, 04 Jul 2024   Prob (F-statistic):               0.00
Time:                        03:31:17   Log-Likelihood:            -1.3113e+05
No. Observations:                8996   AIC:                         2.623e+05
Df Residuals:                    8989   BIC:                         2.623e+05
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.486e+06   4.01e+06     -0.371      0.711   -9.34e+06    6.37e+06
Rooms        4.38e+05   5944.461     73.685      0.000    4.26e+05     4.5e+05
Distance   -4.883e+04   1678.020    -29.098      0.000   -5.21e+04   -4.55e+04
Week         641.9027    999.928      0.642      0.521   -1318.183    2601.989
CPI         1.031e+05   3.47e+04      2.976      0.003    3.52e+04    1.71e+05
LastCPI    -8.764e+04   4.63e+04     -1.893      0.058   -1.78e+05    3096.168
Distance2    372.0547    449.584      0.828      0.408    -509.233    1253.343
==============================================================================
Omnibus:                     4183.474   Durbin-Watson:                   0.634
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            37449.416
Skew:                           2.022   Prob(JB):                         0.00
Kurtosis:                      12.141   Cond. No.                     1.16e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.16e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

# **TRABAJO**

1. Realizar e implementar un modelo de Regresión Multiple Lineal utilizando el conjunto de datos descrito, evaluando e indicando los criterios utilizados(Numéro de atributos, correlacion con la variable objetivo)